### ISSUE TITLE
Port Sparkle code to GemStone

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Sparkle#8]
Since it is turning out that there is a fair amount of code being monkeyed with to get Sparkle to load into GemStone using Rowan, I figure it is worth opening a bug to chronicle the changes that are needed:
- [x] changed package convention to Monticello --- the use of tags is not compatible with RowanHybrid package convention (subset of Monticello), so switched convention to Monticello
- [x] added Announcement class to Sparkle-GemStone as a placeholder until we have an Announcements port to GemStone
- [x] added Announcer class to Sparkle-GemStone as a placeholder until we have an Announcements port to GemStone
- [x] added PackageManifest class to GemStone so that packages with Manifest* classes can be loaded (I'm looking at you Sparkle-Tools-Common)
- [x] [pharo does not follow the same tonel format as used in Rowan](https://github.com/GsDevKit/T2F2T-Conversion/issues/1) ... Rowan reads pharo tonel format, but whenever GemStone or Pharo writes to a common package, there will be a pile of spurious differences because of the differences in file format ... we might be able to patch the Pharo9 tonel write to conform to the format used by Rowan in order to avoid a lot of noise (#11 - Pharo and Rowan tonel writers write definitions in different formats)
- [x] SpkTextServiceServer class removed from Sparkle-GemStone package, since it's superclasses are all in Sparkle-Experiments where there is already a presumably Pharo-specific SpkTextServiceServer class ... 
- [x] #6 - Cannot load Sparkle into GemStone - SpkTestInspectorServiceClient fails because SpkInspectorServiceClient is not present in GemStone
- [x] #7 - Cannot compile serveral methods in SpkTool
- [x] #9 - Cannot compile SpkTaskspaceLayoutTool>>initializeForDefault in GemStone (instance variable SpkTaskspaceLayoutTool has already been declared)
- [x] #10 - Cannot compile several methods in SpkInspectorTool
- [x] #12 - Classes in Sparkle-Tools-Common need to be moved to Sparkle-Tools-Pharo ... 
- [x] #13 - Test package needs to be factored into GemStone tests, Pharo tests, and common tests
